- task: Maven@4
  inputs:
    azureSubscription: 'Azure 订阅 1(012e53b9-740f-44c6-aa64-8ea6b7f3d7d8)'
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
